version: 0.2

phases:
  install:
    commands:
      - npm install -g @angular/cli
  build:
    commands:
      - npm run build --prod
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/testpipeline